packages:
  - .

# Permite que esses pacotes rodem seus scripts de build/postinstall no CI
onlyBuiltDependencies:
  - prisma
  - @prisma/client
  - @prisma/engines
  - sharp
  - esbuild
  - @tailwindcss/oxide

# (opcional) bloqueia explicitamente tudo que NÃO estiver acima
# ignoredBuiltDependencies: []

# (opcional) desativa a lista de "nunca construir" se você por engano setou antes
# neverBuiltDependencies: []
